#!/bin/sh

# fatalign -- script for generating eraseblock-aligned FAT filesystems

# cluster size is fixed to 32k by the SD card standard; this is a good value
# in general for ensuring cluster size is a multiple of page size
CLUSTER_SIZE=32768
SECTORS_PER_CLUSTER=$(($CLUSTER_SIZE/512))

MKDOSFS=/sbin/mkdosfs

. "`dirname $0`"/align.sh

if [ -z "$1" ]; then
	echo "Usage: $0 fs-sectors eraseblock-size [block-device-or-image]"
	exit 0
fi

sdcard_sectors="$1"
eraseblock_size="$2"
[ "$3" ] && filesystem="$3"

reserved_sectors="`align_reserved_sectors $sdcard_sectors $eraseblock_size`"

echo "Data area alignment: $eraseblock_size bytes"
echo "Reserved sectors required: $reserved_sectors"

if [ "$filesystem" ]; then
	exec "$MKDOSFS" -F 32 -s $SECTORS_PER_CLUSTER -R $reserved_sectors -a "$filesystem"
fi

exit 0
