#!/bin/sh

# fatalign -- script for generating eraseblock-aligned FAT filesystems
#
# Copyright (C) 2014 Steven Luo
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# cluster size is fixed to 32k by the SD card standard; this is a good value
# in general for ensuring cluster size is a multiple of page size
CLUSTER_SIZE=32768
SECTORS_PER_CLUSTER=$(($CLUSTER_SIZE/512))

MKDOSFS=/sbin/mkdosfs

. "`dirname $0`"/align.sh

if [ -z "$1" ]; then
	echo "Usage: $0 [-a] fs-sectors eraseblock-size [block-device-or-image]"
	exit 0
fi

if [ x"$1" = x"-a" ]; then
	no_cluster_align=1
	shift
fi

sdcard_sectors="$1"
eraseblock_size="$2"
[ "$3" ] && filesystem="$3"

align_option="cluster_align"
[ "$no_cluster_align" ] && align_option=""
reserved_sectors="`align_reserved_sectors $sdcard_sectors $eraseblock_size $align_option`"

echo "Data area alignment: $eraseblock_size bytes"
echo "Reserved sectors required: $reserved_sectors"

if [ "$filesystem" ]; then
	align_option=""
	[ "$no_cluster_align" ] && align_option="-a"
	exec "$MKDOSFS" -F 32 -s $SECTORS_PER_CLUSTER -R $reserved_sectors $align_option "$filesystem"
fi

exit 0
