#!/bin/sh

# fatalign -- script for generating eraseblock-aligned FAT filesystems
#
# Copyright (C) 2014 Steven Luo
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

MKDOSFS=/sbin/mkdosfs

. "`dirname $0`"/align.sh

if [ x"$1" = x"-a" ]; then
	no_cluster_align=1
	shift
fi

if [ $# -lt 2 ]; then
	echo "Usage: $0 [-a] fs-sectors eraseblock-size [block-device-or-image]"
	exit 0
fi

sdcard_sectors="$1"
eraseblock_size="$2"
[ "$3" ] && filesystem="$3"

align_option="cluster_align"
[ "$no_cluster_align" ] && align_option=""

# Select the largest possible cluster size for this filesystem
cluster_size="`select_cluster_size $sdcard_sectors $eraseblock_size $align_option`"
if [ $cluster_size -lt 512 ]; then
	echo "Filesystem is too small to hold an aligned FAT32 filesystem!"
	exit 1
fi
sectors_per_cluster=$(($cluster_size / 512))

reserved_sectors="`align_reserved_sectors $sdcard_sectors $eraseblock_size $cluster_size $align_option`"

echo "Cluster size: $cluster_size bytes"
echo "Data area alignment: $eraseblock_size bytes"
echo "Reserved sectors required: $reserved_sectors"

if [ "$filesystem" ]; then
	align_option=""
	[ "$no_cluster_align" ] && align_option="-a"
	exec "$MKDOSFS" -F 32 -s $sectors_per_cluster -R $reserved_sectors $align_option "$filesystem"
fi

exit 0
